name: "CI from {{SDK}}"

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ sdk ]
    paths:
      - "sdk/{{SDK}}"
      - ".github/workflows/ci-sdk-{{SDK}}.yaml"

env:
  TOTAL_COVERAGE: ${{ 0.0 }}
  MINIMUM_COVERAGE: ${{ {{MINIMUM_COVERAGE}} }}
      
jobs:
  formal-requirements:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: sdk/{{SDK}}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Get Current Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Permissioned Branch
        run: |
            regex_pattern="^(feature[-/])"
            if [[ "${{ env.BRANCH_NAME }}" =~ $regex_pattern ]]; then 
            echo "The active branch ${{ env.BRANCH_NAME }} is a valid branch." 
            else
            echo "The branch ${{ env.BRANCH_NAME }} is invalid. The pattern expected is feature/*"; exit 1
            fi
  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: {{GO_VERSION}}

      - name: Create Coverage Reports
        run: |
            go clean --testcache
            go test -v -race -coverprofile tmp/coverage.out -json ./... >> tmp/report.json
            echo "TOTAL_COVERAGE=$(go tool cover -func tmp/coverage.out | tail -1 | grep -o '[0-9.]*%' | awk '{print substr($1, 1, length($1)-1)}')" >> $GITHUB_ENV    

      - name: Validate Minimum Coverage
        if: ${{ fromJSON(env.TOTAL_COVERAGE) < fromJSON(env.MINIMUM_COVERAGE) }}
        run: |
            echo "The code doesn't have the expected minimum coverage."
            echo "Coverage ${{env.TOTAL_COVERAGE}} | Minimum ${{env.MINIMUM_COVERAGE}}"
            exit 1

  others-checks:
    needs: formal-requirements
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: sdk/{{SDK}}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: {{GO_VERSION}}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: sdk/{{SDK}}
      
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        env:
          GO111MODULE: on
        with:
          args: ./...

      - name: Create Coverage Reports
        run: |
            go clean --testcache
            go test -v -race -coverprofile tmp/coverage.out -json ./... >> tmp/report.json
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}