name: CI to develop

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, reopened, synchronize ]
  
jobs:
  ci-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Permissioned Branch
        run: |
            regex_pattern="^(bugfix[-/]|feature[-/]|sdk|microservices)"
            if [[ "${{ env.BRANCH_NAME }}" =~ $regex_pattern ]]; then 
            echo "The active branch ${{ env.BRANCH_NAME }} is a valid branch." 
            else
            echo "The branch ${{ env.BRANCH_NAME }} is invalid. The pattern expected is bugfix/*, feature/*, sdk or microservices"; exit 1
            fi
  
  others-checks:
    needs: ci-develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        env:
          GO111MODULE: on  
        with:
          args: ./...

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        env:
          GO111MODULE: off
        with:
          version: latest
          working-directory: ./

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}